version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:12
commands:
  gatsby-build:
    steps:
      - checkout
      - restore_cache:
        keys:
          # when lock file changes, use increasingly general patterns to restore cache
          - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - node-v1-{{ .Branch }}-
          - node-v1-
      - run: npm install
      - save_cache:
        paths:
          - ~/usr/local/lib/node_modules  # location depends on npm version
        key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - restore_cache:
        keys:
        - gatsby-public-cache-{{ .Branch }}
        - gatsby-public-cache-
      - run: GATSBY_CPU_COUNT=2 NODE_OPTIONS="--max-old-space-size=8192" npm run build
      - save_cache:
        key: gatsby-public-cache-{{ .Branch }}
        paths:
          - ./public
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - release:
          filters:
            branches:
              only:
                - master
jobs:
  build:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - gatsby-build
      # - run:
      #     name: Netlify Deploy
      #     command: ./node_modules/.bin/netlify deploy --dir=public --message "deploy preview from $CIRCLE_BRANCH" --auth $NETLIFY_ACCESS_TOKEN
  release:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - gatsby-build
      # - run:
      #     name: Netlify Deploy
      #     command: ./node_modules/.bin/netlify deploy --prod --dir=public --message "deploy from $CIRCLE_BRANCH" --auth $NETLIFY_ACCESS_TOKEN