module.exports = {
  blogTitle: 'Takumon blog',
  blogDescription: '東京でJavaのSIerやってます。',
  blogUrl: 'https://takumon.com',
  blogRssUrl: 'https://takumon.com/rss.xml',
  blogImageUrl: 'https://takumon.com/icons/app-sns.png',
  blogAuthorTwitterUserName: 'inouetakumon',
  blogRepositoryUrl: 'https://github.com/Takumon/blog',
  blogAuthorTwitterUrl: 'https://twitter.com/inouetakumon',
  blogAuthorQiitaUrl: 'https://qiita.com/Takumon',
  blogAuthorGitHubUrl: 'https://github.com/Takumon',
  blogAuthorFacebookUrl: 'https://www.facebook.com/takuto.inoue.54',
  facebookAppId: '1959327667485352',
  blogAuthor: 'Takumon',
  blogAuthorDescription: '東京でJavaのSIerやってます。',
  blogAuthorAvatarUrl: 'https://s.gravatar.com/avatar/37d27f624f8c9c8db6fe6b6581b256f1',
};