on:
  pull_request:

steps:
  - name: checkout
    uses: actions/checkout@v3

  - name: deploy preview version of GatsbyJS to Netlify
    uses: jsmrcaga/action-netlify-deploy@v1.7.2
    id: deploy_preview
    with:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      build_command: npm run build
      build_directory: 'public'
